name: Build and test with Java CI and Maven

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  release:
    name: Build, test, and publish to GitHub repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup the Java version
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'

      # Build and run tests
      - name: Maven package
        run: |
          mvn -ntp -B package

      # Publish to GitHub repository
      - name: Publish package
        run: mvn -Dmaven.test.skip=true deploy -Dregistry=https://maven.pkg.github.com/be.codewriter --batch-mode
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}